Workout Planner/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Workout_Planner.Models;
using Microsoft.AspNetCore.Authorization;

namespace Workout_Planner.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult AddProgram()
        {
            ViewData["Message"] = "Add a Program.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Workout Planner/Controllers/ProgramsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Workout_Planner.Data;
using Workout_Planner.Models.Workout;

namespace Workout_Planner.Controllers
{
    public class ProgramsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ProgramsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Programs
        public async Task<IActionResult> Index()
        {
            return View(await _context.Program.ToListAsync());
        }

        // GET: Programs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var program = await _context.Program
                .SingleOrDefaultAsync(m => m.ID == id);
            if (program == null)
            {
                return NotFound();
            }

            ViewBag.Program = program;

            var programWeeks = await (from w in _context.ProgramWeek
                                     where (w.ProgramID == id)
                                     select w).OrderBy(p => p.WeekSequenceNum).ToListAsync();
            ViewBag.ProgramWeeks = programWeeks;

            return View(program);
        }

        // GET: Programs/Create
        public IActionResult Create()
        {
            return View();
        }

        private void CreateProgramWeeksForProgram(int numberOfWeeks, int programID, int startingNumberOfWeeks = 1)
        {
            int i = startingNumberOfWeeks;

            for (i = startingNumberOfWeeks; i <= numberOfWeeks; i++)
            {
                ProgramWeek week = new ProgramWeek();
                week.ProgramID = programID;
                week.Title = "Week " + i;
                week.WeekSequenceNum = i;
                    
                _context.Add(week);
            }
        }

        // POST: Programs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Title,DaysPerWeek,NumberOfWeeks")] Workout_Planner.Models.Workout.Program program)
        {
            if (ModelState.IsValid)
            {
                _context.Add(program);

                await _context.SaveChangesAsync();

                CreateProgramWeeksForProgram(program.NumberOfWeeks, program.ID);

                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            return View(program);
        }

        // GET: Programs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var program = await _context.Program.SingleOrDefaultAsync(m => m.ID == id);
            if (program == null)
            {
                return NotFound();
            }
            return View(program);
        }

        private void UpdateProgramWeeks(int programID, int prevNumWeeks, int newNumWeeks)
        {
            
            if(prevNumWeeks < newNumWeeks)
            {
                CreateProgramWeeksForProgram(newNumWeeks, programID, prevNumWeeks+1);
            }
            else if (prevNumWeeks > newNumWeeks)
            {
                var weekRange = (from w in _context.ProgramWeek
                                 where (w.ProgramID == programID)
                                 select w).OrderByDescending(p => p.WeekSequenceNum).Take(prevNumWeeks-newNumWeeks);
                _context.ProgramWeek.RemoveRange(weekRange);
            }
        }

        // POST: Programs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Title,DaysPerWeek,NumberOfWeeks")] Workout_Planner.Models.Workout.Program program)
        {
            if (id != program.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var prevNumWeeks =
                        (from w in _context.ProgramWeek
                         where (w.ProgramID == program.ID)
                         select w).Count();
                        // Does not work!
                        //_context.Entry(program).OriginalValues.GetValue<int>("NumberOfWeeks");
                    UpdateProgramWeeks(program.ID,
                        prevNumWeeks,
                        program.NumberOfWeeks);
                    _context.Update(program);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProgramExists(program.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(program);
        }

        // GET: Programs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var program = await _context.Program
                .SingleOrDefaultAsync(m => m.ID == id);
            if (program == null)
            {
                return NotFound();
            }

            return View(program);
        }

        // POST: Programs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var program = await _context.Program.SingleOrDefaultAsync(m => m.ID == id);
            _context.Program.Remove(program);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProgramExists(int id)
        {
            return _context.Program.Any(e => e.ID == id);
        }
    }
}

Workout Planner/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Workout Planner/Views/Home/AddProgram.cshtml
@{
    ViewData["Title"] = "AddProgram";
    Layout = "~/Views/Home/_Layout.cshtml";
}

<body>
    <div id="wrapper">
        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">Add a Workout Program</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            Program Information
                        </div>
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-lg-6">
                                    <form role="form">
                                        <div class="form-group">
                                            <label>Program Name</label>
                                            <input class="form-control" placeholder="Enter Name">
                                        </div>
                                    </form>
                                </div>
                                <!-- /.col-lg-6 (nested) -->

                            </div>
                            <!-- /.row (nested) -->
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->
    </div>
    <!-- /#wrapper -->
</body>

Workout Planner/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Workout Planner/Views/Home/Index.cshtml
<!DOCTYPE html>
<html lang="en">

@{
    ViewData["Title"] = "Index";
}
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

</head>
<body>
    <div id="wrapper">
        <!-- Page Content -->
        <div id="page-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">Blank</h1>
                    </div>
                    <!-- /.col-lg-12 -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->
        </div>
        <!-- /#page-wrapper -->
    </div>
    <!-- /#wrapper -->
    <!-- jQuery -->
    <script src="../vendor/jquery/jquery.min.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="../vendor/bootstrap/js/bootstrap.min.js"></script>
    <!-- Metis Menu Plugin JavaScript -->
    <script src="../vendor/metisMenu/metisMenu.min.js"></script>
    <!-- Custom Theme JavaScript -->
    <script src="../dist/js/sb-admin-2.js"></script>
</body>
</html>

Workout Planner/Views/Home/_Layout.cshtml
@{ 
    Layout = "/Views/Shared/_NavigationLayout.cshtml";
}

<body>
    <nav>
        <div class="navbar-default sidebar" role="navigation" style="margin-top: 0">
            <div class="sidebar-nav navbar-collapse">
                <ul class="nav" id="side-menu">
                    <li class="sidebar-search">
                        <div class="input-group custom-search-form">
                            <input type="text" class="form-control" placeholder="Search...">
                            <span class="input-group-btn">
                                <button class="btn btn-default" type="button">
                                    <i class="fa fa-search"></i>
                                </button>
                            </span>
                        </div>
                        <!-- /input-group -->
                    </li>
                    <li>
                        <a href="index.html"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
                    </li>
                    <li>
                        <a href="tables.html"><i class="fa fa-table fa-fw"></i> Track Workout</a>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-bar-chart-o fa-fw"></i> Workout Plans<span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a asp-area="" asp-controller="Programs" asp-action="Index"> View</a>
                            </li>
                            <li>
                                <a asp-area="" asp-controller="Programs" asp-action="Create"> Create</a>
                            </li>
                        </ul>
                        <!-- /.nav-second-level -->
                    </li>
                    <li>
                        <a href="tables.html"><i class="fa fa-table fa-fw"></i> Workout History</a>
                    </li>
                </ul>
            </div>
            <!-- /.sidebar-collapse -->
        </div>
        <!-- /.navbar-static-side -->
    </nav>
    <div class="container body-content">
        @RenderBody()
    </div>
</body>
    @section Scripts {
        @RenderSection("Scripts", required: false)
    }