Workout Planner/Models/Workout/Program.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Workout_Planner.Models.Workout
{
    public class Program
    {
        public int ID { get; set; }

        [Display(Name = "Program Name"), Required(ErrorMessage = "Program Title is required")]
        public string Title { get; set; }

        [
         Display(Name = "Days per Week"), 
         Required(ErrorMessage = "Number of days per week is required"),
         Range(1, 7, ErrorMessage = "Number of days must be between 1 and 7!")
        ]
        public int DaysPerWeek { get; set; }

        [
         Display(Name = "Number of Weeks"), 
         Required(ErrorMessage = "Number of weeks is required"), 
         Range(1,16,ErrorMessage = "Number of weeks must be between 1 an 16!")
        ]
        public int NumberOfWeeks { get; set; }
    }
}

Workout Planner/Controllers/ProgramsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Workout_Planner.Data;
using Workout_Planner.Models.Workout;

namespace Workout_Planner.Controllers
{
    public class ProgramsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ProgramsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Programs
        public async Task<IActionResult> Index()
        {
            return View(await _context.Program.ToListAsync());
        }

        // GET: Programs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var program = await _context.Program
                .SingleOrDefaultAsync(m => m.ID == id);
            if (program == null)
            {
                return NotFound();
            }

            ViewBag.Program = program;

            var programWeeks = await (from w in _context.ProgramWeek
                                     where (w.ProgramID == id)
                                     select w).OrderBy(p => p.WeekSequenceNum).ToListAsync();
            ViewBag.ProgramWeeks = programWeeks;

            return View(program);
        }

        // GET: Programs/Create
        public IActionResult Create()
        {
            return View();
        }

        private void CreateProgramWeeksForProgram(int numberOfWeeks, int programID, int startingNumberOfWeeks = 1)
        {
            int i = startingNumberOfWeeks;

            for (i = startingNumberOfWeeks; i <= numberOfWeeks; i++)
            {
                ProgramWeek week = new ProgramWeek();
                week.ProgramID = programID;
                week.Title = "Week " + i;
                week.WeekSequenceNum = i;
                    
                _context.Add(week);
            }
        }

        // POST: Programs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Title,DaysPerWeek,NumberOfWeeks")] Workout_Planner.Models.Workout.Program program)
        {
            if (ModelState.IsValid)
            {
                _context.Add(program);

                await _context.SaveChangesAsync();

                CreateProgramWeeksForProgram(program.NumberOfWeeks, program.ID);

                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            return View(program);
        }

        // GET: Programs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var program = await _context.Program.SingleOrDefaultAsync(m => m.ID == id);
            if (program == null)
            {
                return NotFound();
            }
            return View(program);
        }

        private void UpdateProgramWeeks(int programID, int prevNumWeeks, int newNumWeeks)
        {
            
            if(prevNumWeeks < newNumWeeks)
            {
                CreateProgramWeeksForProgram(newNumWeeks, programID, prevNumWeeks+1);
            }
            else if (prevNumWeeks > newNumWeeks)
            {
                var weekRange = (from w in _context.ProgramWeek
                                 where (w.ProgramID == programID)
                                 select w).OrderByDescending(p => p.WeekSequenceNum).Take(prevNumWeeks-newNumWeeks);
                _context.ProgramWeek.RemoveRange(weekRange);
            }
        }

        // POST: Programs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Title,DaysPerWeek,NumberOfWeeks")] Workout_Planner.Models.Workout.Program program)
        {
            if (id != program.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var prevNumWeeks =
                        (from w in _context.ProgramWeek
                         where (w.ProgramID == program.ID)
                         select w).Count();
                        // Does not work!
                        //_context.Entry(program).OriginalValues.GetValue<int>("NumberOfWeeks");
                    UpdateProgramWeeks(program.ID,
                        prevNumWeeks,
                        program.NumberOfWeeks);
                    _context.Update(program);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProgramExists(program.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(program);
        }

        // GET: Programs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var program = await _context.Program
                .SingleOrDefaultAsync(m => m.ID == id);
            if (program == null)
            {
                return NotFound();
            }

            return View(program);
        }

        // POST: Programs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var program = await _context.Program.SingleOrDefaultAsync(m => m.ID == id);
            _context.Program.Remove(program);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProgramExists(int id)
        {
            return _context.Program.Any(e => e.ID == id);
        }
    }
}

Workout Planner/Controllers/WorkoutsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Workout_Planner.Data;
using Workout_Planner.Models.Workout;

namespace Workout_Planner.Controllers
{
    public class WorkoutsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public WorkoutsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Workouts
        public async Task<IActionResult> Index()
        {
            return View(await _context.Workout.ToListAsync());
        }

        // GET: Workouts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var workout = await _context.Workout
                .SingleOrDefaultAsync(m => m.ID == id);
            if (workout == null)
            {
                return NotFound();
            }

            return View(workout);
        }

        // GET: Workouts/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Workouts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,ProgamWeekID,Title,LastCompleted")] Workout workout)
        {
            if (ModelState.IsValid)
            {
                _context.Add(workout);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(workout);
        }

        // GET: Workouts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var workout = await _context.Workout.SingleOrDefaultAsync(m => m.ID == id);
            if (workout == null)
            {
                return NotFound();
            }
            return View(workout);
        }

        // POST: Workouts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,ProgamWeekID,Title,LastCompleted")] Workout workout)
        {
            if (id != workout.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(workout);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!WorkoutExists(workout.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(workout);
        }

        // GET: Workouts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var workout = await _context.Workout
                .SingleOrDefaultAsync(m => m.ID == id);
            if (workout == null)
            {
                return NotFound();
            }

            return View(workout);
        }

        // POST: Workouts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var workout = await _context.Workout.SingleOrDefaultAsync(m => m.ID == id);
            _context.Workout.Remove(workout);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool WorkoutExists(int id)
        {
            return _context.Workout.Any(e => e.ID == id);
        }
    }
}

Workout Planner/Views/Programs/Create.cshtml
@model Workout_Planner.Models.Workout.Program

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Home/_Layout.cshtml";
}

<body>
    <div id="wrapper">
        <div id="page-wrapper">
            <div class="row">
                <div class=""col-xs-12 col-sm-6 col-md-8"">
                    <h1 class="page-header">Add a Workout Program</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    <form asp-action="Create">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="Title" class="control-label"></label>
                            <input asp-for="Title" class="form-control" />
                            <span asp-validation-for="Title" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="DaysPerWeek" class="control-label"></label>
                            <input asp-for="DaysPerWeek" class="form-control" />
                            <span asp-validation-for="DaysPerWeek" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="NumberOfWeeks" class="control-label"></label>
                            <input asp-for="NumberOfWeeks" class="form-control" />
                            <span asp-validation-for="NumberOfWeeks" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Create" class="btn btn-default" />
                        </div>
                    </form>
                </div>

                <div>
                    <a asp-action="Index">Back to List</a>
                </div>
            </div>
        </div>
        <!-- /#page-wrapper -->
    </div>
    <!-- /#wrapper -->
</body>

Workout Planner/Views/Programs/Delete.cshtml
@model Workout_Planner.Models.Workout.Program

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Home/_Layout.cshtml";
}

<h2>Delete</h2>

<body>
    <div id="wrapper">
        <div id="page-wrapper">
            <div class="row">
                <div class="" col-xs-12 col-sm-6 col-md-8"">
                    <h1 class="page-header">Delete Program</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <div>
                <h4>Are you sure you want to delete @Html.DisplayFor(model => model.Title)?</h4>
                <hr />
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    <form asp-action="Delete">
                        <input type="hidden" asp-for="ID" />
                        <input type="submit" value="Yes" class="btn btn-default" /> 
                        <a asp-action="Index" class="btn btn-default">No</a>
                    </form>
                </div>

                @*<div>
                <a asp-action="Index">Back to List</a>
            </div>*@
            </div>
        </div>
        <!-- /#page-wrapper -->
    </div>
    <!-- /#wrapper -->
</body>

Workout Planner/Views/Programs/Details.cshtml
@model Workout_Planner.Models.Workout.Program

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Home/_Layout.cshtml";
}

<body>
    <div id="wrapper">
        <div id="page-wrapper">
            <div class="row">
                <div class="" col-xs-12 col-sm-6 col-md-8"">
                    <h1 class="page-header"> @Html.DisplayFor(model => model.Title)</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            Collapsible Accordion Panel Group
                        </div>
                        <!-- .panel-heading -->
                        <div class="panel-body">
                            <div class="panel-group" id="accordion">
                                @{
                                    int i = 1;
                                    foreach (var week in ViewBag.programWeeks)
                                    {
                                        <div class="panel panel-default">
                                            <div class="panel-heading">
                                                <h4 class="panel-title">
                                                    <a data-toggle="collapse" data-parent="#accordion" href="@("#collapse"+ i)">@week.Title</a>
                                                </h4>
                                            </div>
                                            <div id="@("collapse" + i)" class="panel-collapse collapse in">
                                                <div class="panel-body">
                                                    <button type="button" class="btn btn-primary">
                                                        <a asp-area="" asp-controller="Workouts" asp-action="Create"><i class="fa fa-plus"></i> Add Workout</a>
                                                    </button>
                                                </div>
                                            </div>
                                        </div>
                                        i++;
                                    }
                                }
                            </div>
                        </div>
                        <!-- .panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
            </div>
        </div>
        <!-- /#page-wrapper -->
    </div>
    <!-- /#wrapper -->
</body>

Workout Planner/Views/Programs/Edit.cshtml
@model Workout_Planner.Models.Workout.Program

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Home/_Layout.cshtml";
}

<h2>Edit</h2>

<body>
    <div id="wrapper">
        <div id="page-wrapper">
            <div class="row">
                <div class="" col-xs-12 col-sm-6 col-md-8"">
                    <h1 class="page-header">Edit Program</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    <form asp-action="Edit">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <input type="hidden" asp-for="ID" />
                        <div class="form-group">
                            <label asp-for="Title" class="control-label"></label>
                            <input asp-for="Title" class="form-control" />
                            <span asp-validation-for="Title" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="DaysPerWeek" class="control-label"></label>
                            <input asp-for="DaysPerWeek" class="form-control" />
                            <span asp-validation-for="DaysPerWeek" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="NumberOfWeeks" class="control-label"></label>
                            <input asp-for="NumberOfWeeks" class="form-control" />
                            <span asp-validation-for="NumberOfWeeks" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Save" class="btn btn-default" />
                        </div>
                    </form>
                    <div>
                        <a asp-action="Index">Back to List</a>
                    </div>
                </div>
            </div>
        </div>
        <!-- /#page-wrapper -->
    </div>
    <!-- /#wrapper -->
</body>

Workout Planner/Views/Programs/Index.cshtml
@model IEnumerable<Workout_Planner.Models.Workout.Program>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Home/_Layout.cshtml";
}

<h2>Index</h2>

<body>
    <div id="wrapper">
        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">Add a Workout Program</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    <p>
                        <a asp-action="Create">Create New</a>
                    </p>
                    <table class="table">
                        <thead>
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.Title)
                                </th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Title)
                                </td>
                                <td>
                                    <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                                    <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                                    <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
                                </td>
                            </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <!-- /.col-lg-12 -->
            </div>
        </div>
        <!-- /#page-wrapper -->
    </div>
    <!-- /#wrapper -->
</body>